---
output: html_document
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="css/academicons.min.css"/>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\


## Working papers 

<font size="+1">

* Pettenuzzo, D., [Sabbatucci, R.](https://sites.google.com/site/riccardosabbatucci/) [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/)  Financial Statements and Macroeconomic Dynamics (August 2024) \
[[Link to SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4922676) &nbsp; &nbsp; [[Data]](http://www.corporateactivitytracker.com)

>What do companies' 10-Q filings reveal about the state of the macro economy and do specific accounting variables contain particularly relevant information? To address these questions, we analyze the lead-lag patterns of more than twenty accounting variables in relation to aggregate economic activity. We develop new daily corporate account business activity indices that aggregate firm-level accounting information while controlling for shifts in the composition of announcers and reducing firm-specific noise. Our new indices show that firm liquidity becomes significantly lower while corporate debt grows significantly faster several months prior to recessions, and thus can be used as leading indicators. Conversely, operations, earnings, and profitability measures tend to be significantly lower after recessions, suggesting they are mostly lagging, pro-cyclical indicators of economic activity.

* [Carriero, A.](https://www.qmul.ac.uk/sef/staff/andreacarriero.html), Pettenuzzo, D, [Shekhar, S.](https://shubhranshu-shekhar.github.io) Macroeconomic Forecasting with Large Language Models (June 2024) \
[[Link to SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4881094)  &nbsp; &nbsp; [[Slides]](files/2024_09_20 Forecasting_with_LLMs (slides).pdf)

>This paper presents a comparative analysis evaluating the accuracy of Large Language Models (LLMs) against traditional macro time series forecasting approaches. In recent times, LLMs have surged in popularity for forecasting due to their ability to capture intricate patterns in data and quickly adapt across very different domains. However, their effectiveness in forecasting macroeconomic time series data compared to conventional methods remains an area of interest. To address this, we conduct a rigorous evaluation of LLMs against traditional macro forecasting methods, using as common ground the FRED-MD database. Our findings provide valuable insights into the strengths and limitations of LLMs in forecasting macroeconomic time series, shedding light on their applicability in real-world scenarios.

## Published and forthcoming articles

<font size="+1">

1. [Chan, J.](https://joshuachan.org), Pettenuzzo, D., [Poon, A.](https://sites.google.com/view/aubreybcpoon/home?authuser=0), [Zhu, D.](https://research.monash.edu/en/persons/dan-zhu) (2025), Conditional Forecasts in Large Bayesian VARs with Multiple Equality and Inequality Constraints , __Journal of Economic Dynamics and Control__, 173\
[[Published version]](https://www.sciencedirect.com/science/article/pii/S0165188925000272?via%3Dihub) &nbsp; &nbsp; [[Link to SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4358152) 

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Sabbatucci, R.](https://sites.google.com/site/riccardosabbatucci/) (2023), Payout suspensions during the Covid-19 pandemic, __Economics Letters__, 224:111024 \
[[Published version]](https://www.sciencedirect.com/science/article/pii/S0165176523000496) &nbsp; &nbsp;

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Sabbatucci, R.](https://sites.google.com/site/riccardosabbatucci/) (2023), Dividend Suspensions and Cash Flows During the Covid-19 Pandemic: A Dynamic Econometric Model, __Journal of Econometrics__, 235:1522--1541  \
[[Published version]](https://www.sciencedirect.com/science/article/pii/S030440762300012X?via%3Dihub) &nbsp; &nbsp; [[Working paper]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3628608)  

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Yong, S.](https://sites.google.com/view/ysong1) (2022), Corrigendum to “Predictability of stock returns and asset allocation under structural breaks” [J. Econometrics 164 (2011) 60–78], __Journal of Econometrics__, 227: 513-517 \
[[Published version]](https://www.sciencedirect.com/science/article/pii/S0304407621000476) &nbsp; &nbsp;

1. [Korobilis, D.](https://sites.google.com/site/dimitriskorobilis/), Pettenuzzo, D. (2020) Machine Learning Econometrics: Bayesian Algorithms and Methods, __Oxford Research Encyclopedia: Economics and Finance__  \
[[Published version]](https://doi.org/10.1093/acrefore/9780190625979.013.588) &nbsp; &nbsp; [[Working paper]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3580433) &nbsp; &nbsp; 

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Sabbatucci, R.](https://sites.google.com/site/riccardosabbatucci/) (2020) Cash Flow News and Stock Price Dynamics, __Journal of Finance__, 75: 2221-2270    
[[Published version]](https://doi.org/10.1111/jofi.12901) &nbsp; &nbsp; [[Working paper]](http://ssrn.com/abstract=3127042) &nbsp; &nbsp; [[Online Appendix]](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fjofi.12901&file=jofi12901-sup-0001-OnlineAppendix.pdf)  

1. [Carvalho, C.](http://faculty.mccombs.utexas.edu/carlos.carvalho/personal.html), [Fisher, J.](https://www.linkedin.com/pub/jared-fisher/21/809/362), Pettenuzzo, D. (2020) Optimal Asset Allocation with Multivariate Bayesian Dynamic Linear Models, __Annals of Applied Statistics__, 14: 299-338
\
[[Published version]](https://projecteuclid.org/euclid.aoas/1587002676) &nbsp; &nbsp; [[Working paper]](http://ssrn.com/abstract=3254935) &nbsp; &nbsp;  

1. [Pan, Z.](https://www.researchgate.net/profile/Zhiyuan_Pan2), Pettenuzzo, D., [Wang, Y.](https://www.researchgate.net/profile/Yudong_Wang12/publications) (2020) Forecasting Stock Returns: A Predictor-constrained Approach __Journal of Empirical Finance__, 55: 200-217
\
  [[Published version]](https://doi.org/10.1016/j.jempfin.2019.11.008) &nbsp; &nbsp; [[Working paper]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3054652) &nbsp; &nbsp;  

1. [Korobilis, D.](https://sites.google.com/site/dimitriskorobilis/), Pettenuzzo, D. (2019) Adaptive Hierarchical Priors for High-Dimensional Vector Autoregressions, __Journal of Econometrics__, 212: 241-271 \
[[Published version]](https://doi.org/10.1016/j.jeconom.2019.04.029) &nbsp; &nbsp; [[Working paper]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2886053) &nbsp; &nbsp;  


1. [Koop, G.](http://personal.strath.ac.uk/gary.koop/), [Korobilis, D.](https://sites.google.com/site/dimitriskorobilis/) , Pettenuzzo, D. (2019) Bayesian Compressed Vector Autoregressions, __Journal of Econometrics__, 210: 135-154 \
  [[Published version]](https://doi.org/10.1016/j.jeconom.2018.11.009) &nbsp; &nbsp; [[Working paper]](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2754241) &nbsp; &nbsp; [[Online Appendix]](files/2017_06_05_BCVAR_Appendix.pdf) 

 
1. [Gargano, A.](http://fbe.unimelb.edu.au/finance/staff/academic/2524), Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/) (2019) Bond Return Predictability: Economic Value and Links to the Macroeconomy, __Management Science__,  65: 508-540  
[[Published version]](http://pubsonline.informs.org/doi/abs/10.1287/mnsc.2017.2829) &nbsp; &nbsp; [[Working paper]](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2471273) &nbsp; &nbsp; [[Online Appendix]](files/2017_04_18_bond_return_predictability_ON_LINE_APPENDIX.pdf) 
 
1. [Metaxoglou, K.](http://carleton.ca/economics/people/metaxoglou-konstantinos/), Pettenuzzo, D., [Smith, A.](http://are.ucdavis.edu/en/people/faculty/aaron-smith/#pk_campaign=short-name-redirect&pk_kwd=asmith) (2019) Option-Implied Equity Premium Predictions via Entropic Tilting, __Journal of Financial Econometrics__,  17: 559-586  
[[Published version]](https://academic.oup.com/jfec/article/17/4/559/4990347?guestAccessKey=20547485-7185-4cfb-aee6-c318b438e544) &nbsp; &nbsp; [[Working paper]](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2754246) &nbsp; &nbsp; [[Online Appendix]](files/MPS_JFEC_APX.pdf) 

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/) (2017) Forecasting Macroeconomic Variables Under Model Instability, __Journal of Business and Economic Statistics__, 35: 183-201  
[[Published version]](http://www.tandfonline.com/doi/abs/10.1080/07350015.2015.1051183) &nbsp; &nbsp; [[Working paper]](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2603879) &nbsp; &nbsp; [[Online Appendix]](files/Appendix_JBES_2015_May_5.pdf)  

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Valkanov, R.](http://rady.ucsd.edu/faculty/directory/valkanov/) (2016) A MIDAS Approach to Modeling First and Second Moment Dynamics, __Journal of Econometrics__, 193: 315-334  
[[Published version]](http://www.sciencedirect.com/science/article/pii/S0304407616300665) &nbsp; &nbsp; [[Working paper]](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2471287)

1. Pettenuzzo, D., [Ravazzolo, F.](http://francescoravazzolo.com/) (2016) Optimal Potfolio Choice under Decision-Based Model Combinations, __Journal of Applied Econometrics__, 31: 1312-1332  
[[Published version]](http://onlinelibrary.wiley.com/doi/10.1002/jae.2502/abstract) &nbsp; &nbsp; [[Working paper]](http://ssrn.com/abstract=2516950) &nbsp; &nbsp; [[Online Appendix]](files/Pettenuzzo_Ravazzolo_JAE_Appendix_Nov04.pdf)

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Valkanov, R.](http://rady.ucsd.edu/faculty/directory/valkanov/)  (2014) Forecasting Stock Returns under Economic Constraints,  __Journal of Financial Economics__, 114: 517-553  
[[Published version]](http://dx.doi.org/10.1016/j.jfineco.2014.07.015) &nbsp; &nbsp; [[Working paper]](files/2013.12.02 Pettenuzzo_Timmermann_Valkanov.pdf)

1. Pettenuzzo, D., [White, H.](http://economics.ucsd.edu/facRes/inMemoriam/whiteHalbert/) (2014) Granger Causality, Exogeneity, Cointegration, and Economic Policy Analysis, __Journal of Econometrics__, 178: 316-330  
[[Published version]](http://www.sciencedirect.com/science/article/pii/S0304407613001942) &nbsp; &nbsp; [[Working paper]](files/2011_10_31 Pettenuzzo and White.pdf)

1. Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/) (2011) Predictability of Stock Returns and Asset Allocation under Structural Breaks,  __Journal of Econometrics__, 164: 60-78  
[[Published version]](http://www.sciencedirect.com/science/article/pii/S0304407611000479) &nbsp; &nbsp; [[Working paper]](files/Pettenuzzo and Timmermann (2011).pdf) &nbsp; &nbsp; [[Matlab codes]](files/2011 JoE codes.zip)

1. [Pesaran, H.](http://dornsife.usc.edu/cf/faculty-and-staff/faculty.cfm?pid=1003600), Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/) (2007) Learning, Structural Instability, and Present Value Calculations, __Econometric Reviews__, 26: 253-288  
[[Published version]](http://www.tandfonline.com/doi/abs/10.1080/07474930701220352) &nbsp; &nbsp; [[Working paper]](files/Pesaran et al (2007).pdf)

1. [Pesaran, H.](http://dornsife.usc.edu/cf/faculty-and-staff/faculty.cfm?pid=1003600), Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/) (2006) Forecasting Time Series subject to Structural Breaks, __Review of Economic Studies__, 73: 1057-1084    
[[Published version]](http://restud.oxfordjournals.org/content/73/4/1057.full) &nbsp; &nbsp; [[Working paper]](files/Pesaran et al (2006).pdf) &nbsp; &nbsp; [[Matlab codes]](files/2006 ReStud codes.zip)

\


## Work in progress and older working papers

<font size="+1">

* Pettenuzzo, D., [Poon, A.](https://sites.google.com/view/aubreybcpoon/home?authuser=0), [Zhu, D.](https://research.monash.edu/en/persons/dan-zhu), Modeling and Forecasting Count Data with Vector Autoregressions 

* [Kastner, G.](https://www.wu.ac.at/en/statmath/faculty-staff/faculty/gkastner/), Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/) Modeling Stock-Bond Correlations

* Pettenuzzo, D., [Sabbatucci, R.](https://sites.google.com/site/riccardosabbatucci/) The Term Structure and Cross-Section of Cash Flow Risk (January 2023)\
[[Link to SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4241054)  
  + _INQUIRE 2020 Europe Research Grant_

* Pettenuzzo, D., [Timmermann, A.](http://rady.ucsd.edu/faculty/directory/timmermann/), [Sabbatucci, R.](https://sites.google.com/site/riccardosabbatucci/) Firm Value and Payout Suspensions During Financial Market Distress (August 2022)\
[[Link to SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3823258)  





